console_title_template = '{{ .UserName }}@{{ .HostName }} in {{ .PWD }}'
version = 3
final_space = true

[transient_prompt]
  style = 'plain'
  template = '> '
  foreground = '#00ff00'
  type = 'text'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = '╭─'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    foreground = '#000000'
    background = '#d3d7cf'
    type = 'os'

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ .Path }} '
    foreground = '#e4e4e4'
    powerline_symbol = ''
    background = '#3465a4'
    type = 'path'

    [blocks.segments.properties]
      home_icon = '~'
      max_depth = 3
      style = 'mixed'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#000000'
    powerline_symbol = ''
    background = '#4e9a06'
    type = 'git'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#4e9a06{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}  '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#689f63'
    type = 'node'
    invert_powerline = true

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#00acd7'
    type = 'go'
    invert_powerline = true

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#4063D8'
    type = 'julia'
    invert_powerline = true

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Venv }}{{ .Venv }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#FFDE57'
    type = 'python'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'context'
      fetch_virtual_env = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#AE1401'
    type = 'ruby'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#FEAC19'
    type = 'azfunc'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}  '
    foreground = '#ffffff'
    powerline_symbol = ''
    type = 'aws'
    background_templates = ['{{if contains "default" .Profile}}#FFA400{{end}}', '{{if contains "jan" .Profile}}#f1184c{{end}}']
    invert_powerline = true

    [blocks.segments.properties]
      display_default = false

  [[blocks.segments]]
    style = 'powerline'
    template = '  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#ffff66'
    type = 'root'
    invert_powerline = true

  [[blocks.segments]]
    # style = 'powerline'
    style = 'diamond'
    template = ' {{ .FormattedMs }}  '
    foreground = '#000000'
    leading_diamond = ""
    # powerline_symbol = ''
    background = '#c4a000'
    type = 'executiontime'
    invert_powerline = true

  [[blocks.segments]]
    style = 'diamond'
    template = ' {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} '
    foreground = '#00ff00'
    # powerline_symbol = ''
    trailing_diamond = ""
    # leading_diamond = ""
    leading_diamond = ""
    background = '#000000'
    type = 'status'
    foreground_templates = ['{{ if gt .Code 0 }}#d3d7cf{{ end }}']
    background_templates = ['{{ if gt .Code 0 }}#cc2222{{ end }}']
    invert_powerline = true

    [blocks.segments.properties]
      always_enabled = true

  # this is the new stuff
  [[blocks.segments]]
    type = "session"
    style = "diamond"
    powerline_symbol = ''
    foreground = "#ffffff"
    # background = "#c386f1"
    background = "#0070e1"
    # leading_diamond = ""
    trailing_diamond = ""
    template = "{{ if .SSHSession }} {{ end }} {{ .UserName }}@{{ .HostName }} "

  [[blocks.segments]]
    style = 'diamond'
    trailing_diamond = '─╮'
    template = ' {{ .CurrentDate | date .Format }}  '
    foreground = '#000000'
    background = '#d3d7cf'
    type = 'time'
    invert_powerline = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '╰─'
    foreground = '#d3d7cf'
    type = 'text'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    style = 'plain'
    template = '─╯'
    foreground = '#d3d7cf'
    type = 'text'
